name: LReport
main: ldcr.LReport.Main
version: 5.0
author: Ldcr
depend: ["LdcrUtils"]
softdepend: ["BattlEye"]
commands:
  report:
    description: report some l hacker.
    usage: /report
  crpt:
    description: report some l hacker - console only.
    usage: /crpt
  lpt:
    description: lol
    usage: /lpt
permissions:
  lreport.lpt:
    description: 管理举报的权限
    default: op
