name: LReport
main: ldcr.LReport.LReport
version: 6
author: Ldcr
depend: ["LdcrUtils"]
softdepend: ["BattlEye"]
commands:
  report:
  crpt:
  staff:
  lpt:
permissions:
  lreport.lpt:
    description: 管理举报的权限
    default: op
  lreport.staff:
    description: 管理志愿者举报的权限
    default: op

