name: SakuraReport
main: sakura.kooi.SakuraReport.SakuraReport
version: 5
author: SakuraKooi
depend: ["SakuraUtils"]
commands:
  report:
  sakuraconsolereport:
      aliases: [sakuracpt, scpt]
  sakurastaffreport:
      aliases: [sakura]
  sakurareport:
      aliases: [spt]
permissions:
  sakurareport.manage:
    description: 管理举报的权限
    default: op
  sakurareport.staff:
    description: 管理志愿者举报的权限
    default: op

